[project]
name = "megaconf"
version = "0.1.0"
description = "Easily create many variations of a config."
readme = "README.md"
authors = [
    { name = "Richard Wessels" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/RichardWessels/megaconf"
Issues = "https://github.com/RichardWessels/megaconf/issues"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
